spring:
  datasource:
    url: jdbc:mysql://localhost/movieApi
    username: root
    password: Skmania@1234
    
  jpa:
    hibernate:
      ddl-auto: update
    
    show-sql: true
    properties:
      hibernate:
        format_sql: true
